GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/someInvalidId

###

DELETE http://localhost:3001/api/persons/65cb5e028858ec30d80c02df

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "ff",
    "number": "050-776-30-43"
}

###

PUT http://localhost:3001/api/persons/65cca2a9cb6d359087b627e3
Content-Type: application/json

{
    "name": "bb",
    "number": "999 99 99"
}